strategies:
- input_format: '{{text}}'
  model: openrouter/anthropic/claude-3.5-sonnet
  output_name: outline
  prompt_name: academic_outliner
- input_format: 'outline:

    {{outline}}

    search result:

    {{text}}

    '
  model: openrouter/anthropic/claude-3.5-sonnet
  output_name: outline_filled
  prompt_name: academic_fill_outline_with_material
- input_format: 'outline filled:

    {{outline_filled}}

    search result:

    {{text}}

    '
  model: openrouter/anthropic/claude-3.5-sonnet
  output_name: literature_review_section
  prompt_name: literature_review_exa
