strategies:
- input_format: 'original text:

    {{text}}

    vocabularies:

    {{memory_vocab}}

    '
  model: openai/gpt-4o
  output_name: correction
  prompt_name: correct_cn_audio_transcription
- input_format: 'original text:

    {{text}}

    advice on vocabulary correction:

    {{correction}}

    '
  model: openai/gpt-4o
  output_name: reflection
  prompt_name: comment_cn_audio_transcription
- input_format: 'original text:

    {{text}}

    reflection:

    {{reflection}}

    '
  model: openrouter/openai/gpt-4o-mini
  output_name: improvement
  prompt_name: improve_transcription_wsy_cn
