strategies:
- input_format: '{{text}}'
  output_name: exa_news_result
  tool_name: exa_search
  tool_params:
    category: news
- input_format: '{{text}}'
  output_name: exa_tweet_result
  tool_name: exa_search
  tool_params:
    category: tweet
- input_format: 'user input text: {{text}} search result: {{exa_news_result}} {{exa_tweet_result}}'
  model: openrouter/anthropic/claude-3-5-sonnet-20240620
  output_name: outlined_result
  prompt_name: outliner_wsy
- input_format: 'user input text:

    {{outlined_result}}

    blog example: {{memory_blog_example}}'
  model: openrouter/anthropic/claude-3-5-sonnet
  output_name: tech_blog_draft
  prompt_name: write_wsy_tech_blog
