strategies:
- input_format: '{{text}}'
  model: openrouter/openai/gpt-4o-mini
  output_name: translation
  prompt_name: translate_en
- input_format: 'original text:

    {{text}}

    translation:

    {{translation}}

    '
  model: openrouter/anthropic/claude-3.5-sonnet
  output_name: reflection
  prompt_name: comment_en_trans
- input_format: 'original text:

    {{text}}

    translation:

    {{translation}}

    comments:

    {{reflection}}

    '
  model: openrouter/openai/gpt-4o-mini
  output_name: improvement
  prompt_name: improved_trans_en
